name: Deploy

# Trigger the workflow on push and
# pull request events on the main branch
on:
  push:
    branches: ["main"]

# Allow this job to clone the repo and create a page deployment
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: wcag
    steps:
      - name: Checkout your repository using git
        uses: actions/checkout@v3
      - name: Install, build, and upload your site
        uses: withastro/action@v1
      - name: Create folder
        run: |
          mkdir -p /home/github/animate2024.fossee.in/prod && cp -R dist /home/github/animate2024.fossee.in/prod
