name: Deploy to GitHub Pages

on:
  # Trigger the workflow every time you push to the `main` branch
  # Using a different branch name? Replace `main` with your branch’s name
  push:
    branches: [ main ]
  # Allows you to run this workflow manually from the Actions tab on GitHub.
  workflow_dispatch:

# Allow this job to clone the repo and create a page deployment
permissions:
  contents: read
  pages: write
  id-token: write
jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Install yarn
        run: |
          npm run install-yarn-package
          yarn run yarn-install --frozen-lockfile
      - name: Checkout your repository using git
        uses: actions/checkout@v3
      - name: Install, build, and upload your site
        uses: withastro/action@v1
      - name: Create folder
        run: |
          mkdir -p /home/github/animate2024.fossee.in/prod && cp -R dist /home/github/animate2024.fossee.in/prod
